# Generated by Django 5.2.3 on 2025-07-03 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_alter_booking_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_time',
            new_name='booked_at',
        ),
    ]
